# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Blog.create(title: "First Post", text: "My name is Mary Katherine Blackwood. I am eighteen years old, and I live with my sister Constance. I have often thought that with any luck at all I could have been born a werewolf, because the two middle fingers on both my hands are the same length, but I have had to be content with what I had. I dislike washing myself, and dogs, and noise. I like my sister Constance, and Richard Plantagenet, and Amanita phalloides, the death-cup mushroom. Everyone else in my family is dead.")
Blog.create(title: "Second Post", text: "No live organism can continue for long to exist sanely under conditions of absolute reality; even larks and katydids are supposed, by some, to dream. Hill House, not sane, stood by itself against its hills, holding darkness within; it had stood so for eighty years and might stand for eighty more. Within, walls continued upright, bricks met nearly, floors were firm, and doors were sensibly shut; silence lay steadily against the wood and stone of Hill House, and whatever walked there, walked alone.")
Blog.create(title: "Third Post", text: "Mr. Arnold Waite–husband, parent, man of his word–invariably leaned back in his chair after his second cup of breakfast coffee and looked with some disbelief at his wife and two children. His chair was situated so that when he put his head back the sunlight, winter or summer, touched his unfaded hair with an air at once angelic and indifferent–indifferent because, like himself, it found belief not an essential factor to its continued existence. When Mr. Waite turned his head to regard his wife and children the sunlight moved with him, broken into patterns on the table and floor.")
Blog.create(title: "Fourth Post", text: "Although the museum was well known to be a seat of enormous learning, its foundations had begun to sag. This produced in the building an odd, and disturbingly apparent, list to the west, and in the daughters of the town, whose energetic borrowings had raised the funds to sustain the museum, infinite shame and a tendency to blame one another. It was at the same time a cause of much amusement among the museum personnel, whose several vocations were most immediately affected by the decided slant given to the floors of their building. The proprietor of the dinosaur was, as a matter of fact, very humorous about the almost foetal tilt of his august bones, and the numismatist, whose specimens tended to slide together and jar one another, was heard to remark–almost to tedium–upon the classical juxtapositions thus achieved.")
Blog.create(title: "Fifth Post", text: "I do not now have the slightest understand of the events which got us out of one big white house which we rented into another, bigger white house which we own, at least in part. That is, I know we moved, and I think I know why, and I know we spent three pleasant months in a friend’s summer home, and I am pretty sure we got most of our own furniture back. What really puzzles me, I suppose, is how a series of events like that gets itself started.")
Blog.create(title: "Sixth Post", text: "After the funeral they came back to the house, now indisputably Mrs. Halloran’s. They stood uneasily, without any certainty, in the large lovely entrance hall, and watched Mrs. Halloran go into the right wing of the house to let Mr. Halloran know that Lionel’s last rites had gone off without melodrama. Young Mrs. Halloran, looking after her mother-in-law, said without hope, 'Maybe she will drop dead on the doorstep. Fancy, dear, would you like to see Granny drop dead on the doorstep?'")